### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by keeponZhang** [CTSN/testWxPay#1]
取消订单或者支付成功后，再次支付时会显示参数错误。

**Comment by CTSN** [comment]
重新生成预支付id了？

**Comment by mrk2nk2n** [comment]
在运行案例时也遇见这个问题，在新歌手机上运行，能够支付一次，接着重新调起的时候就会有参数错误的问题。

**Comment by CTSN** [comment]
@mrk2nk2n 你好，参数错误可以看下log日志，微信是有返回信息。项目中生成预支付id这一步，是交由服务端生成的，客户端只负责调起，本demo只做演示用
